revisiting C

diff --git a/bin/install-and-monitor b/bin/install-and-monitor
--- a/bin/install-and-monitor
+++ b/bin/install-and-monitor
@@ -9,9 +9,16 @@ fi
 
 dir=$1
 
+# This path might be Ubuntu or Debian specific.
+pico="/media/$USER/RPI-RP2/"
+if ! [ -e "$pico" ]; then
+  >&2 printf 'Error: The expected mass storage location %s was not found.\n' "$pico"
+  >&2 printf 'Is the Pico in boot select mode?\n'
+  exit 2
+fi
+
 printf 'Copying uf2 file to Pico mass storage device.\n'
-# This might be Ubuntu or Debian specific.
-cp "$dir/build-bin/co2.uf2" /media/david/RPI-RP2/
+cp "$dir/build-bin/co2.uf2" "$pico"
 
 printf 'Waiting for /dev/ttyACM0 '
 while ! [ -e /dev/ttyACM0 ]; do
